name: hello_platform_windows
description: Windows implementation of the hello plugin
version: 1.0.0
author: Hakkyu Kim

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: HelloPlatformWindowsPlugin
