name: hello
description: The app facing package of the hello plugin
version: 1.0.0
author: Hakkyu Kim
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  hello_platform_interface:
    path: ../hello_platform_interface
