name: hello_platform_interface
description: A common platform interface for the hello plugin
version: 1.0.0
author: Hakkyu Kim

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"